server:
  servlet:
    context-path: /api/v1/poli
  port: 9081
spring:
  application:
    name: customer
  profiles:
    active: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
